# Generated by Django 4.0.4 on 2022-06-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(blank=True, default='', max_length=30)),
                ('phone', models.IntegerField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=20)),
                ('adress', models.CharField(blank=True, default='', max_length=40)),
                ('bith', models.DateField(blank=True, null=True)),
                ('info', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Babys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bith', models.DateField(blank=True, null=True)),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.clients')),
            ],
        ),
    ]
