# Generated by Django 4.0.4 on 2022-06-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_orders_status_alter_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='id_service',
            new_name='service',
        ),
    ]
