# Generated by Django 4.0.4 on 2022-07-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_clients_adress_alter_clients_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='bith',
        ),
    ]
