# Generated by Django 4.0.4 on 2022-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_remove_clients_bith'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='bith',
            field=models.DateField(blank=True, null=True),
        ),
    ]
