# Generated by Django 4.0.4 on 2022-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_clients_bith'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
