# Generated by Django 4.0.4 on 2022-07-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='bith',
        ),
    ]
