# Generated by Django 4.0.4 on 2022-07-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_clients_name_alter_clients_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
