# Generated by Django 4.0.4 on 2022-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_clients_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('show', models.BooleanField()),
                ('newborn', models.BooleanField()),
            ],
        ),
    ]
