# Generated by Django 4.0.4 on 2022-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babys',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
