# Generated by Django 4.0.4 on 2022-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_alter_babys_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babys',
            name='id_parent',
            field=models.IntegerField(),
        ),
    ]
