# Generated by Django 4.0.4 on 2022-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_alter_babys_id_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='bith',
            field=models.DateField(blank=True, null=True),
        ),
    ]
