# Generated by Django 4.0.4 on 2022-07-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_clients_bith'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['name', 'surname']},
        ),
    ]
