# Generated by Django 4.0.4 on 2022-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_alter_clients_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babys',
            old_name='id_parent',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.IntegerField(),
        ),
    ]
