# Generated by Django 4.0.4 on 2022-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_alter_orders_client_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='info',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
