# Generated by Django 4.0.4 on 2022-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_alter_orders_client_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
