# Generated by Django 4.0.4 on 2022-07-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_alter_orders_client_alter_orders_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
