# Generated by Django 4.0.4 on 2022-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0036_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='info',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
